# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
        env:
          CI: true
          # testの設定
          # ここでは、srcディレクトリ配下の__tests__ディレクトリと、
          # srcディレクトリ配下の.spec.js、.test.js拡張子のファイルをテスト対象とする
          # また、.test.jsファイルが存在するディレクトリの中にはテスト対象外のものがあるため、
          # そのディレクトリをtestPathIgnorePatternsに指定している
          # 参考：https://jestjs.io/docs/configuration#testmatch-arraystring
          working-directory: ./src
          continue-on-error: ${{ matrix.continue_on_error }}
#          with:
#            args: ["--testLocationInResults", "--testPathPattern=/src/**/__tests__/**/*.{js,jsx,ts,tsx},/src/**/*.{spec,test}.{js,jsx,ts,tsx}", "--testPathIgnorePatterns=/src/**/*.test.js"]

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm install
      - name: ESLint
        run: npx eslint .
